### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by menelaos**

### CODE REVIEW

**Comment by menelaos** [comment]
@zudov It would be really cool if you could release `purescript-var` with psc-0.10 compatible version bounds as `purescript-localstorage` depends on this lib.

**Comment by jamesthompson** [comment]
Is there anything holding up merging this?

**Comment by zudov** [comment]
Looks good. Thanks for the bump.

Sorry for a delay, I'll wrap a release today.

**Comment by jamesthompson** [comment]
Thanks @zudov Any chance you could bump your websockets lib deps too? 
Thanks a lot for all the hard work on this stuff. It's great!

**Pull request merged**
